apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
          app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysqldb
          image: mysql:5.7
          env: 
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: 1234qweR
            - name: MYSQL_DATABASE
              value: db
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
    ports:
      - port: 3306
        protocol: TCP
    selector:
      app: mysql
    