apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  labels:
    app: wp
spec:
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
        - image: wordpress:php7.4-apache
          name: wp
          ports:
            - containerPort: 80
              name: wp
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service.default.svc.cluster.local
            - name: WORDPRESS_DB_USER
              value: user
            - name: WORDPRESS_DB_PASSWORD
              value: 1234qweR
            - name: WORDPRESS_DB_NAME
              value: db
            - name: WORDPRESS_DEBUG
              value: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: wp-service
spec:
    type: LoadBalancer
    selector:
        app: wp
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 80
    